// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/offers": {
    params: {};
  };
  "/app/offers/:id": {
    params: {
      "id": string;
    };
  };
  "/app/design": {
    params: {};
  };
  "/app/analytics": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/orders/create": {
    params: {};
  };
  "/webhooks/compliance": {
    params: {};
  };
  "/api/beacon": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/auth/*" | "/app" | "/app/offers" | "/app/offers/:id" | "/app/design" | "/app/analytics" | "/app/settings" | "/webhooks/app/uninstalled" | "/webhooks/app/scopes_update" | "/webhooks/orders/create" | "/webhooks/compliance" | "/api/beacon";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/offers" | "/app/offers/:id" | "/app/design" | "/app/analytics" | "/app/settings";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.offers._index.tsx": {
    id: "offers-index";
    page: "/app/offers";
  };
  "routes/app.offers.$id.tsx": {
    id: "routes/app.offers.$id";
    page: "/app/offers/:id";
  };
  "routes/app.design.tsx": {
    id: "routes/app.design";
    page: "/app/design";
  };
  "routes/app.analytics.tsx": {
    id: "routes/app.analytics";
    page: "/app/analytics";
  };
  "routes/app.settings.tsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.orders.create.tsx": {
    id: "routes/webhooks.orders.create";
    page: "/webhooks/orders/create";
  };
  "routes/webhooks.compliance.tsx": {
    id: "routes/webhooks.compliance";
    page: "/webhooks/compliance";
  };
  "routes/api.beacon.tsx": {
    id: "routes/api.beacon";
    page: "/api/beacon";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "offers-index": typeof import("./app/routes/app.offers._index.tsx");
  "routes/app.offers.$id": typeof import("./app/routes/app.offers.$id.tsx");
  "routes/app.design": typeof import("./app/routes/app.design.tsx");
  "routes/app.analytics": typeof import("./app/routes/app.analytics.tsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.orders.create": typeof import("./app/routes/webhooks.orders.create.tsx");
  "routes/webhooks.compliance": typeof import("./app/routes/webhooks.compliance.tsx");
  "routes/api.beacon": typeof import("./app/routes/api.beacon.tsx");
};